name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: 'composer'

      - name: ðŸ“¦ Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          php composer.phar install --no-dev --prefer-dist --optimize-autoloader --ignore-platform-reqs
          
      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.INFOMANIAK_FTP_SERVER }}
          username: ${{ secrets.INFOMANIAK_FTP_USERNAME }}
          password: ${{ secrets.INFOMANIAK_FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: ./sites/laboiteanuggets.ch/
